services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: ../.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - app_log_data:/app/logs
      - app_media_data:/app/storage

  postgres:
    image: postgres:18-alpine
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:alpine
    env_file: ../.env
    ports:
      - "6379:6379"
    volumes:
      - redist_data:/data
    restart: on-failure

volumes:
  postgresql_data:
  redist_data:
  app_log_data:
  app_media_data: